# Generated by Django 3.0.7 on 2020-11-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccess', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_auth',
            field=models.BooleanField(default=False),
        ),
    ]
