# Generated by Django 3.0.7 on 2020-11-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccess', '0002_customuser_is_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_auth',
            field=models.BooleanField(default='0'),
        ),
    ]
