# Generated by Django 3.0.7 on 2020-11-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccess', '0003_auto_20201110_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_auth',
        ),
        migrations.AddField(
            model_name='customuser',
            name='code',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
