# Generated by Django 3.0.7 on 2020-11-10 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccess', '0005_auto_20201110_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
