# Generated by Django 3.0.7 on 2020-11-11 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccess', '0006_auto_20201111_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='Truth', max_length=60, unique=True),
        ),
    ]
